name = "web-tools-url-shortener"
main = "src/worker/short-links/worker.ts"
compatibility_date = "2026-07-12"

[[d1_databases]]
binding = "DB"
database_name = "web-tools-url-shortener"
database_id = "00000000-0000-0000-0000-000000000000"
migrations_dir = "src/worker/short-links/migrations"
